name: Laravel CI/CD

on:
  workflow_call:
    secrets:
      deploy-hook:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from reusable workflow"
